export const createTickets = (userIds: string[]) => [
  {
    title: "Implement User Authentication",
    description: "Set up secure user authentication with Auth.js v5",
    status: "DONE" as const,
    bounty: 250099,
    deadline: new Date("2025-07-12"),
    userId: userIds[0],
  },
  {
    title: "Create Ticket Management System",
    description: "Build a comprehensive ticket management interface",
    status: "OPEN" as const,
    bounty: 120099,
    deadline: new Date("2025-09-12"),
    userId: userIds[0],
  },
  {
    title: "Add Real-time Notifications",
    description: "Implement WebSocket-based real-time notifications",
    status: "IN_PROGRESS" as const,
    bounty: 25099,
    deadline: new Date("2025-06-28"),
    userId: userIds[1],
  },
  {
    title: "Optimize Database Queries",
    description: "Improve database performance with query optimization",
    status: "OPEN" as const,
    bounty: 75000,
    deadline: new Date("2025-08-15"),
    userId: userIds[1],
  },
  {
    title: "Design Mobile App UI",
    description: "Create responsive mobile app interface design",
    status: "OPEN" as const,
    bounty: 180000,
    deadline: new Date("2025-10-01"),
    userId: userIds[2],
  },
  {
    title: "Fix Critical Security Bug",
    description: "Address SQL injection vulnerability in user input handling",
    status: "IN_PROGRESS" as const,
    bounty: 500000,
    deadline: new Date("2025-05-20"),
    userId: userIds[0],
  },
  {
    title: "Implement Dark Mode Toggle",
    description: "Add theme switching functionality with persistent user preferences",
    status: "OPEN" as const,
    bounty: 45000,
    deadline: new Date("2025-08-30"),
    userId: userIds[1],
  },
  {
    title: "Create API Documentation",
    description: "Generate comprehensive API documentation using OpenAPI/Swagger",
    status: "OPEN" as const,
    bounty: 85000,
    deadline: new Date("2025-09-15"),
    userId: userIds[2],
  },
  {
    title: "Add Unit Test Coverage",
    description: "Increase test coverage to 80% for critical business logic",
    status: "DONE" as const,
    bounty: 95000,
    deadline: new Date("2025-06-10"),
    userId: userIds[0],
  },
  {
    title: "Implement Search Functionality",
    description: "Add full-text search with filters and sorting options",
    status: "OPEN" as const,
    bounty: 150000,
    deadline: new Date("2025-10-20"),
    userId: userIds[1],
  },
  {
    title: "Setup CI/CD Pipeline",
    description: "Configure automated testing and deployment workflow",
    status: "IN_PROGRESS" as const,
    bounty: 120000,
    deadline: new Date("2025-07-25"),
    userId: userIds[2],
  },
  {
    title: "Performance Optimization",
    description: "Reduce page load times and improve overall application performance",
    status: "OPEN" as const,
    bounty: 200000,
    deadline: new Date("2025-11-05"),
    userId: userIds[0],
  },
  {
    title: "Add Multi-language Support",
    description: "Implement internationalization (i18n) for multiple languages",
    status: "OPEN" as const,
    bounty: 175000,
    deadline: new Date("2025-12-01"),
    userId: userIds[1],
  },
  {
    title: "Create Admin Dashboard",
    description: "Build comprehensive admin panel for user and system management",
    status: "OPEN" as const,
    bounty: 300000,
    deadline: new Date("2025-11-15"),
    userId: userIds[2],
  },
  // Additional tickets for pagination testing
  {
    title: "Implement File Upload System",
    description: "Add secure file upload functionality with image compression",
    status: "OPEN" as const,
    bounty: 125000,
    deadline: new Date("2025-09-20"),
    userId: userIds[0],
  },
  {
    title: "Add Email Notifications",
    description: "Implement email notification system for ticket updates",
    status: "IN_PROGRESS" as const,
    bounty: 80000,
    deadline: new Date("2025-08-10"),
    userId: userIds[1],
  },
  {
    title: "Create User Profile Pages",
    description: "Build detailed user profile pages with activity history",
    status: "OPEN" as const,
    bounty: 95000,
    deadline: new Date("2025-10-15"),
    userId: userIds[2],
  },
  {
    title: "Implement Data Export",
    description: "Add CSV/Excel export functionality for ticket data",
    status: "OPEN" as const,
    bounty: 65000,
    deadline: new Date("2025-09-05"),
    userId: userIds[0],
  },
  {
    title: "Add Advanced Filtering",
    description: "Implement advanced filtering and sorting for ticket lists",
    status: "IN_PROGRESS" as const,
    bounty: 110000,
    deadline: new Date("2025-08-25"),
    userId: userIds[1],
  },
  {
    title: "Create Reporting Dashboard",
    description: "Build analytics dashboard with charts and metrics",
    status: "OPEN" as const,
    bounty: 180000,
    deadline: new Date("2025-11-30"),
    userId: userIds[2],
  },
  {
    title: "Implement Rate Limiting",
    description: "Add API rate limiting to prevent abuse",
    status: "OPEN" as const,
    bounty: 70000,
    deadline: new Date("2025-08-15"),
    userId: userIds[0],
  },
  {
    title: "Add Social Login",
    description: "Implement OAuth login with Facebook and Twitter",
    status: "IN_PROGRESS" as const,
    bounty: 90000,
    deadline: new Date("2025-09-10"),
    userId: userIds[1],
  },
  {
    title: "Create Mobile App",
    description: "Develop native mobile app for iOS and Android",
    status: "OPEN" as const,
    bounty: 400000,
    deadline: new Date("2025-12-20"),
    userId: userIds[2],
  },
  {
    title: "Implement Caching Layer",
    description: "Add Redis caching for improved performance",
    status: "OPEN" as const,
    bounty: 130000,
    deadline: new Date("2025-10-05"),
    userId: userIds[0],
  },
  {
    title: "Add Voice Commands",
    description: "Implement voice command functionality for accessibility",
    status: "OPEN" as const,
    bounty: 220000,
    deadline: new Date("2025-11-25"),
    userId: userIds[1],
  },
  {
    title: "Create Integration API",
    description: "Build REST API for third-party integrations",
    status: "IN_PROGRESS" as const,
    bounty: 160000,
    deadline: new Date("2025-09-30"),
    userId: userIds[2],
  },
  {
    title: "Implement Backup System",
    description: "Add automated backup and recovery system",
    status: "OPEN" as const,
    bounty: 140000,
    deadline: new Date("2025-10-30"),
    userId: userIds[0],
  },
  {
    title: "Add Video Conferencing",
    description: "Integrate video conferencing for team collaboration",
    status: "OPEN" as const,
    bounty: 280000,
    deadline: new Date("2025-12-10"),
    userId: userIds[1],
  },
];
